### ISSUE TITLE
[Important Suggestion] Allow changing the port

### ISSUE THREAD

**Issue by The-Nyla** [8bitFra/JustIRC#6]
I can connect to my IRC server, which is not using the default port, from an IRC client, but trying to connect to it using JustIRC doesn't seem to work, I used the format IP:PORT in the server address field in the config, but it continues to give the error "Unknown Host", from what I can tell I think that JustIRC is still trying to connect to the default IRC port, it would be nice if you could add a field in the config to configure the port.

**Comment by 8bitFra** [comment]
Thanks for the suggestion, actually this is an important problem that I hadn't evaluated.  I will integrate the functionality as soon as I find the time to update to Minecraft 1.20.

**Comment by The-Nyla** [comment]
Thanks! I tried messing around with the code myself to add that functionality by adding a new “port” field in the config, but I only know very basic Java and kept running into a few errors that I couldn’t fix

**Comment by 8bitFra** [comment]
problem solved https://github.com/8bitFra/JustIRC/releases/tag/v1.0.9
